import axios from 'axios';
import React, { useState } from 'react';
import toast from 'react-hot-toast';
import { Link, useNavigate } from 'react-router-dom';
import { useGoogleLogin } from "@react-oauth/google";
import { GoogleLoginButton } from "react-social-login-buttons";

export default function Login() {
    const [step, setStep] = useState(0);
    return (
        <div>
            {step === 0 && <CheckEmailPage setStep={setStep} />}
            {step === 1 && <CheckPasswordPage />}
        </div>
    );
}

export function CheckEmailPage({ setStep }) {
    const [user, setUser] = useState({ email: "" });
    const navigate = useNavigate();

    const handleOnChange = (event) => {
        setUser({ ...user, [event.target.name]: event.target.value });
    };

    const handleOnClick = async (event) => {
        event.preventDefault();
        try {
            const response = await axios.post(`${process.env.REACT_APP_SERVER_URL}/api/email`, user);
            localStorage.setItem("userId", response.data.checkEmail._id);
            localStorage.setItem("name", response.data.checkEmail.name);
            localStorage.setItem("profile_pic", response.data.checkEmail.profile_pic);
            toast.success(response.data.message);
            setStep(1);
        } catch (error) {
            toast.error(error?.response?.data?.message || "An error occurred.");
            console.log(error);
        }
    };

    const handleContinueWithGoogle = useGoogleLogin({
        onSuccess: async (res) => {
            try {
                const userData = await axios.get("https://www.googleapis.com/oauth2/v3/userinfo", {
                    headers: { 'Authorization': `Bearer ${res.access_token}` }
                });
                console.log(userData)
                const newUser = {
                    name: userData.data.name,
                    email: userData.data.email,
                    profile_pic: userData.data.picture,
                    autoGenerated: true
                };
                toast.loading("Logging in through Google...");
                console.log(newUser)
                const response = await axios.post(`${process.env.REACT_APP_SERVER_URL}/api/password`, newUser);
                localStorage.setItem("token", response.data.token);
                navigate('/user');
                toast.dismiss();
                toast.success(response.data.message);
            } catch (error) {
                toast.dismiss();
                toast.error(error?.response?.data?.message || "An error occurred.");
                console.log(error);
            }
        },
        onError: (error) => {
            console.log(error);
        }
    });

    return (
        <div className='mainwindow'>
            <div className="social">
                <GoogleLoginButton style={{ width: "46px", height: "46px", borderRadius: "100%" }} text="" onClick={handleContinueWithGoogle} />
            </div>
            <div className='formwindow'>
                <h1>Enter your email</h1>
                <form className='form'>
                    <input type="email" name="email" value={user.email} onChange={handleOnChange} placeholder='Enter your email' />
                    <button onClick={handleOnClick}>Enter Password</button>
                    <Link to="/register" className='signin'>Signup?</Link>
                </form>
            </div>
        </div>
    );
}

export function CheckPasswordPage() {
    const profile_pic = localStorage.getItem("profile_pic");
    const name = localStorage.getItem("name");
    const localuserId = localStorage.getItem("userId");
    const navigate = useNavigate();
    const [user, setUser] = useState({ password: "", userId: localuserId });

    const handleOnChange = (event) => {
        setUser((prev) => ({ ...prev, [event.target.name]: event.target.value }));
    };

    const handleOnClick = async (e) => {
        e.preventDefault();
        try {
            toast.loading("Logging in...");
            const response = await axios.post(`${process.env.REACT_APP_SERVER_URL}/api/password`, user);
            toast.dismiss();
            toast.success(response.data.message);
            navigate("/user");
            localStorage.clear();
            localStorage.setItem("token", response.data.token);
        } catch (error) {
            toast.dismiss();
            toast.error(error?.response?.data?.message || "An error occurred.");
        }
    };

    return (
        <div className='mainwindow'>
            <div className='formwindow'>
                <h2>Please enter your password</h2>
                <form className='form'>
                    {profile_pic && <img src={profile_pic} alt={name} />}
                    <input
                        type="password"
                        name="password"
                        value={user.password}
                        onChange={handleOnChange}
                        placeholder='Enter your password'
                    />
                    <button onClick={handleOnClick}>Login</button>
                    <Link to="/register" className='signin'>Signup?</Link>
                </form>
            </div>
        </div>
    );
}